server:
  port: 8080

spring:
  profiles:
    active: awss3
  cloud:
    config:
      server:
        awss3:
          bucket: ttcare-remote-config-test
          region: ap-northeast-1
  application:
    name: config-server

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: ${eureka.server.url}
    region: ${eureka.region}